apiVersion: serving.knative.dev/v1
kind: Service
metadata:
    name: serverless-app
spec:
    template:
        metadata:
            annotations:
                autoscaling.knative.dev/target: "10"
        spec:
            containers:
                - image: docker.io/leoalmeida99/serverless-app:1.0-SNAPSHOT